config/routes.rb
Rails.application.routes.draw do
  root to: "pages#index"
  get "listyourorganisation" => "pages#list_your_org"

  resources :organisations
  resources :subjects
  resource :search

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  get "logout" => "sessions#destroy"

  get "register" => "users#new"
  post "register" => "users#create"
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :organisation
  enum c_types: [:phone, :mobile, :email, :fax, :website]
  validates_inclusion_of :c_type, in: Contact.c_types.keys
end

app/models/council.rb
class Council < ActiveRecord::Base
end

app/models/dataset.rb
class Dataset < ActiveRecord::Base
  has_many :organisations
end

app/models/organisation.rb
class Organisation < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  index_name [Rails.env, self.base_class.to_s.pluralize.underscore].join('_')

  has_many :contacts, dependent: :destroy
  has_many :organisation_subjects
  has_many :subjects, through: :organisation_subjects

  belongs_to :street_state, class_name: "State", foreign_key: "street_state_id"
  belongs_to :post_state, class_name: "State", foreign_key: "post_state_id"
  belongs_to :dataset

  validates :name, presence: true
  validates :dataset, presence: true

  accepts_nested_attributes_for :contacts, allow_destroy: true
  has_attached_file :logo, styles: { normal: "100x100" }, default_url: "images/:style/missing.png"
  validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/

  scope :starts_with, -> (letter) { where("name LIKE :prefix", prefix: "#{letter}%") }

  def as_indexed_json(options = {}) 
    as_json(
      only: [:name, :aka, :comment, :services],
      include: [:subjects]
    )
  end
end

app/models/organisation_subject.rb
class OrganisationSubject < ActiveRecord::Base
  belongs_to :organisation, class_name: "Organisation"
  belongs_to :subject, class_name: "Subject"
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :street_addresses, class_name: "Organisation", foreign_key: "street_state_id"
  has_many :postal_addresses, class_name: "Organisation", foreign_key: "post_state_id"
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_many :child_links, class_name: "SubjectLink", foreign_key: "parent_id"
  has_many :children, through: :child_links

  has_many :parent_links, class_name: "SubjectLink", foreign_key: "child_id"
  has_many :parents, through: :parent_links

  has_many :organisation_subjects
  has_many :organisations, through: :organisation_subjects

  scope :top_level, -> { includes(:parent_links).where( subject_links: { parent_id: nil } ) }

  scope :starts_with, -> (letter) { where("name LIKE :prefix", prefix: "#{letter}%") }
end

app/models/subject_link.rb
class SubjectLink < ActiveRecord::Base
  belongs_to :child, class_name: "Subject"
  belongs_to :parent, class_name: "Subject"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :username, presence: true
  validates :email, presence: true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone, presence: true
  validates :mobile, presence: true
  validates :position, presence: true
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def list_your_org
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def index

  end

  def show
    if params[:search]
      searcher = SearchService.new(Organisation)
      @results = searcher.search(params[:search])
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_by(email: params[:email])
    if @user and @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:notice] = "User authenticated"
    else
      flash[:alert] = "Invalid username or password"
    end

    redirect_to "/"
  end

  def destroy

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    flash[:notice] = "Could not create user" unless @user.save
    redirect_to "/"
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :first_name, :last_name, :password, :password_confirmation, :position, :phone, :mobile)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/organisations_helper.rb
module OrganisationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Almanac" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">SACommunity</a>

        <div class="pull-right top-logos visible-lg visible-md visible-sm">
          <%= image_tag("logo_cu.png") %>
          <%= image_tag("logo_sa.png") %>
          <%= image_tag("logo_gov.png") %>
        </div>

        <div class="visible-xs">
          <div class="navbar-collapse collapse navbar-responsive-collapse">
            <%= render "shared/menu" %>
          </div>
        </div>
      </div>
    </div>

    <div class="search-container row">
      <div class="col-sm-2">
      </div>

      <div class="col-sm-8">
        <div class="row">
          <%= form_tag("/search", class: "form-group", method: :get)  do %>

            <div class="col-sm-6 form-group">
              <%= label_tag "Search the directory"  %>
              <%= text_field_tag :search, nil, class: "form-control search-field", placeholder: "eg Red Cross, arthritis, cricket" %>
            </div>

            <div class="col-sm-4 form-group">
              <%= label_tag "Location"  %>
              <%= select_tag :councils, options_from_collection_for_select(Council.all, "id", "name"), class: "form-control seach-field" %>
            </div>

            <div class="col-sm-2 form-group">
              <%= submit_tag :submit, class: "btn btn-default" %> 
            </div>
          <% end %>
        </div>
      </div>

      <div class="col-sm-2">
      </div>

    </div>
    
    <div class="menu-container row hidden-xs">
      <div class="col-sm-2">
      </div>

      <div class="col-sm-10">
        <%= render "shared/menu" %>
      </div>
    </div>

    <div class="container main-container">
      <div class="row">
        <div class="col-lg-8">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-4">
          <%= image_tag "A-Z_2015.jpg" %>
        </div>
      </div><!--/row-->

      <footer>
      <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/pages/index.html.erb
<div class="jumbotron">
  <h1> Welcome to SAcommunity! </h1>
  <p>
  SAcommunity is South Australia's community information directory. Its purpose is to enable you to
  <ul>
    <li> find out about help available from government, non-government and community services throughout SA </li>
    <li> find out how you can connect with and get involved in your communit </li>
  </ul>
  </p>

  <%= link_to "Browse today!", "/test", class: "btn btn-primary" %>
</div>

<div class="row">
  <div class="col-md-6">
    <div class="thumbnail">
      <h3> Browse the directory </h3>
      <p>
      Slow-carb post-ironic aesthetic master cleanse, marfa stumptown organic polaroid gluten-free kogi. Pitchfork fanny pack vinyl plaid offal mixtape. Raw denim seitan chartreuse listicle brunch lomo. Deep v swag cliche butcher letterpress umami. Ugh kombucha stumptown narwhal listicle roof party, lumbersexual celiac occupy cliche flannel mixtape truffaut. Scenester yr forage, narwhal blog direct trade vegan venmo jean shorts wolf put a bird on it taxidermy. Blue bottle squid authentic organic, artisan williamsburg street art you probably haven't heard of them vinyl stumptown.
      </p>
    </div>
  </div>

  <div class="col-md-6">
    <div class="thumbnail">
      <h3> Signup for our newsletter </h3>
      <p>
      Slow-carb post-ironic aesthetic master cleanse, marfa stumptown organic polaroid gluten-free kogi. Pitchfork fanny pack vinyl plaid offal mixtape. Raw denim seitan chartreuse listicle brunch lomo. Deep v swag cliche butcher letterpress umami. Ugh kombucha stumptown narwhal listicle roof party, lumbersexual celiac occupy cliche flannel mixtape truffaut. Scenester yr forage, narwhal blog direct trade vegan venmo jean shorts wolf put a bird on it taxidermy. Blue bottle squid authentic organic, artisan williamsburg street art you probably haven't heard of them vinyl stumptown.
      </p>
    </div>
  </div>
</div>

app/views/pages/list_your_org.html.erb
<div id="list-your-org">
  Listing your organisation on SAcommunity is <b>free</b>. 
  You must have an account on our system in order to add a listing. 
  Organisations submitted are subject to approval by Connecting Up . Please follow the steps outlined below:

  <h2> 1. Does your organisation meet our criteria? </h2>
  <p>
  Organisations are eligible for inclusion on our site if they are non-profit and provide services that are available to the community. Full criteria are available here.
  </p>


  <h2> 2. Do you have an account on SACommunity? </h2>
  <h3> Yes </h3>
  <ul>
    <li> Log in using your username and password </li>
    <li> <%= link_to "Create a new organisation.", new_organisation_path %> Please add all relevent information </li>
  </ul>
  <h3> No </h3>
  <ul>
    <li> Please register to create your account </li>
    <li> Log in using your username and password </li>
    <li> <%= link_to "Create a new organisation.", new_organisation_path %> Please add all relevent information </li>
  </ul>

  <h2> 3. What happens next? </h2>
  <p> Organisations that are added to SAcommunity will be moderated to ensure that </p>
  <ul>
    <li> They meet our criteria </li>
    <li> Sufficient details are included </li>
    <li> There is compliance with our editorial style </li>
    <li> They do not duplicate existing content </li>
  </ul>
  <p> After you have added an organisation, you can log in again at any time to change or update details as required. </p>
  <p> Connecting Up retains editorial control and reserves the right to exclude organisations that do not meet the criteria, and to modify content to comply with our style and standards. </p>

  <h2> 4. Any questions? </h2>
  <p> Please contact us </p>

</div>

app/views/shared/_menu.html.erb
<ul class="nav navbar-nav">
  <li> <%= link_to "Home", root_path %> </li>
  <li class="dropdown"> 
    <a class="dropdown-toggle" data-toggle="dropdown" href="/test" role="button" aria-haspopup="true" aria-expanded="false"> About <span class="caret"></span> </a>
    <ul class="dropdown-menu">
      <li> <%= link_to "SAcommunity", "/test" %> </li>
      <li> <%= link_to "SAcommunity News", "/test" %> </li>
      <li> <%= link_to "Contact", "/test" %> </li>
      <li> <%= link_to "Sponsors", "/test" %> </li>
    </ul>
  </li>
  <li> <%= link_to "A-Z Organisations", organisations_path(limit: "A") %> </li>
  <li> <%= link_to "A-Z Services", subjects_path(limit: "A") %> </li>
  <li> <%= link_to "Add a listing", listyourorganisation_path %> </li>
  <li> <%= link_to "Blog", "/test" %> </li>
  <li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="/test" role="button" aria-haspopup="true" aria-expanded="false"> User <span class="caret"></span> </a>
    <ul class="dropdown-menu">
      <li> <%= link_to "Log in", login_path %> </li>
      <li> <%= link_to "Register", register_path %> </li>
    </ul>  
  </li>
  <li> <%= link_to "sa.gov.au", "/test" %> </li>
</ul>